/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b13bba67-1abf-4df7-a441-382c6f920c97",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dU6Rdakfl",
    "aws_user_pools_web_client_id": "6q0ecs4ufpu233sk47e8e0qumd",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://4heaoofh3zcmpb2di54ibocipa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4it3embh6bfllir2pxfeu6lv6u",
    "aws_user_files_s3_bucket": "amplify-webdemo1-staging-110334-deployment110334-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
